// Generated by scripts/gen-types.py from supabase/migrations. Do not edit by hand.
// Shape matches `supabase gen types typescript`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          id: string
          table_name: string
          record_id: string | null
          action: string
          actor_id: string | null
          old_values: Json | null
          new_values: Json | null
          occurred_at: string
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          table_name: string
          record_id?: string | null
          action: string
          actor_id?: string | null
          old_values?: Json | null
          new_values?: Json | null
          occurred_at?: string
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          table_name?: string
          record_id?: string | null
          action?: string
          actor_id?: string | null
          old_values?: Json | null
          new_values?: Json | null
          occurred_at?: string
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      crew_settlements: {
        Row: {
          id: string
          driver_id: string
          period_start: string
          period_end: string
          trips_count: number
          gross_amount: number
          deductions: number
          net_amount: number
          status: string
          approved_by: string | null
          paid_at: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          driver_id: string
          period_start: string
          period_end: string
          trips_count?: number
          gross_amount?: number
          deductions?: number
          net_amount?: number
          status?: string
          approved_by?: string | null
          paid_at?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          driver_id?: string
          period_start?: string
          period_end?: string
          trips_count?: number
          gross_amount?: number
          deductions?: number
          net_amount?: number
          status?: string
          approved_by?: string | null
          paid_at?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crew_settlements_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "crew_settlements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "crew_settlements_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_sites: {
        Row: {
          id: string
          customer_id: string
          name: string
          area: string
          latitude: number | null
          longitude: number | null
          geofence_radius_m: number
          directions: string | null
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          name: string
          area: string
          latitude?: number | null
          longitude?: number | null
          geofence_radius_m?: number
          directions?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          customer_id?: string
          name?: string
          area?: string
          latitude?: number | null
          longitude?: number | null
          geofence_radius_m?: number
          directions?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_sites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_sites_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          id: string
          name: string
          phone: string
          alt_phone: string | null
          customer_type: string
          payment_terms: string
          credit_load_cap: number
          credit_days: number
          is_active: boolean
          notes: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          name: string
          phone: string
          alt_phone?: string | null
          customer_type?: string
          payment_terms?: string
          credit_load_cap?: number
          credit_days?: number
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          phone?: string
          alt_phone?: string | null
          customer_type?: string
          payment_terms?: string
          credit_load_cap?: number
          credit_days?: number
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      diesel_issues: {
        Row: {
          id: string
          trip_id: string | null
          truck_id: string
          driver_id: string | null
          litres: number
          price_per_litre: number
          total_cost: number
          issued_at: string
          issued_by: string | null
          note: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          trip_id?: string | null
          truck_id: string
          driver_id?: string | null
          litres: number
          price_per_litre: number
          total_cost: number
          issued_at?: string
          issued_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          trip_id?: string | null
          truck_id?: string
          driver_id?: string | null
          litres?: number
          price_per_litre?: number
          total_cost?: number
          issued_at?: string
          issued_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "diesel_issues_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diesel_issues_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diesel_issues_issued_by_fkey"
            columns: ["issued_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diesel_issues_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diesel_issues_truck_id_fkey"
            columns: ["truck_id"]
            isOneToOne: false
            referencedRelation: "trucks"
            referencedColumns: ["id"]
          },
        ]
      }
      diesel_prices: {
        Row: {
          id: string
          price_per_litre: number
          effective_from: string
          effective_to: string | null
          set_by: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          price_per_litre: number
          effective_from?: string
          effective_to?: string | null
          set_by?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          price_per_litre?: number
          effective_from?: string
          effective_to?: string | null
          set_by?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "diesel_prices_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diesel_prices_set_by_fkey"
            columns: ["set_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      drivers: {
        Row: {
          id: string
          profile_id: string | null
          full_name: string
          phone: string
          licence_number: string | null
          assigned_truck_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          profile_id?: string | null
          full_name: string
          phone: string
          licence_number?: string | null
          assigned_truck_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          profile_id?: string | null
          full_name?: string
          phone?: string
          licence_number?: string | null
          assigned_truck_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "drivers_assigned_truck_id_fkey"
            columns: ["assigned_truck_id"]
            isOneToOne: false
            referencedRelation: "trucks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drivers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drivers_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ledger_entries: {
        Row: {
          id: string
          customer_id: string
          entry_type: string
          amount: number
          payment_id: string | null
          trip_id: string | null
          reverses_entry_id: string | null
          description: string
          occurred_at: string
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          entry_type: string
          amount: number
          payment_id?: string | null
          trip_id?: string | null
          reverses_entry_id?: string | null
          description: string
          occurred_at?: string
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          customer_id?: string
          entry_type?: string
          amount?: number
          payment_id?: string | null
          trip_id?: string | null
          reverses_entry_id?: string | null
          description?: string
          occurred_at?: string
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ledger_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_reverses_entry_id_fkey"
            columns: ["reverses_entry_id"]
            isOneToOne: false
            referencedRelation: "ledger_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      material_sources: {
        Row: {
          id: string
          name: string
          material: string
          area: string | null
          latitude: number | null
          longitude: number | null
          default_material_cost: number
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          name: string
          material: string
          area?: string | null
          latitude?: number | null
          longitude?: number | null
          default_material_cost?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          material?: string
          area?: string | null
          latitude?: number | null
          longitude?: number | null
          default_material_cost?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "material_sources_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          id: string
          order_number: string
          customer_id: string
          site_id: string
          route_id: string
          material: string
          trips_ordered: number
          price_per_trip: number
          route_price_id: string | null
          status: string
          payment_terms: string
          notes: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          order_number?: string
          customer_id: string
          site_id: string
          route_id: string
          material: string
          trips_ordered: number
          price_per_trip: number
          route_price_id?: string | null
          status?: string
          payment_terms: string
          notes?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          order_number?: string
          customer_id?: string
          site_id?: string
          route_id?: string
          material?: string
          trips_ordered?: number
          price_per_trip?: number
          route_price_id?: string | null
          status?: string
          payment_terms?: string
          notes?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_route_id_fkey"
            columns: ["route_id"]
            isOneToOne: false
            referencedRelation: "routes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_route_price_id_fkey"
            columns: ["route_price_id"]
            isOneToOne: false
            referencedRelation: "route_prices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "customer_sites"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          id: string
          customer_id: string
          amount: number
          method: string
          bank_reference: string | null
          received_at: string
          confirmed_by: string | null
          note: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          customer_id: string
          amount: number
          method: string
          bank_reference?: string | null
          received_at: string
          confirmed_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          customer_id?: string
          amount?: number
          method?: string
          bank_reference?: string | null
          received_at?: string
          confirmed_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_confirmed_by_fkey"
            columns: ["confirmed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          full_name: string
          phone: string | null
          role: string
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id: string
          full_name: string
          phone?: string | null
          role: string
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          full_name?: string
          phone?: string | null
          role?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      route_prices: {
        Row: {
          id: string
          route_id: string
          customer_price: number
          material_cost: number
          diesel_price_per_litre: number
          crew_cost: number
          effective_from: string
          effective_to: string | null
          set_by: string | null
          note: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          route_id: string
          customer_price: number
          material_cost: number
          diesel_price_per_litre: number
          crew_cost?: number
          effective_from?: string
          effective_to?: string | null
          set_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          route_id?: string
          customer_price?: number
          material_cost?: number
          diesel_price_per_litre?: number
          crew_cost?: number
          effective_from?: string
          effective_to?: string | null
          set_by?: string | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "route_prices_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "route_prices_route_id_fkey"
            columns: ["route_id"]
            isOneToOne: true
            referencedRelation: "routes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "route_prices_set_by_fkey"
            columns: ["set_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      routes: {
        Row: {
          id: string
          name: string
          source_id: string
          destination_area: string
          distance_km: number | null
          diesel_allowance_litres: number
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          name: string
          source_id: string
          destination_area: string
          distance_km?: number | null
          diesel_allowance_litres: number
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          source_id?: string
          destination_area?: string
          distance_km?: number | null
          diesel_allowance_litres?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "routes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routes_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "material_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      trip_events: {
        Row: {
          id: string
          trip_id: string
          event_type: string
          actor_id: string | null
          occurred_at: string
          latitude: number | null
          longitude: number | null
          note: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          trip_id: string
          event_type: string
          actor_id?: string | null
          occurred_at?: string
          latitude?: number | null
          longitude?: number | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          trip_id?: string
          event_type?: string
          actor_id?: string | null
          occurred_at?: string
          latitude?: number | null
          longitude?: number | null
          note?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trip_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trip_events_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trip_events_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      trip_photos: {
        Row: {
          id: string
          trip_id: string
          photo_type: string
          storage_path: string
          latitude: number | null
          longitude: number | null
          taken_at: string | null
          uploaded_by: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          trip_id: string
          photo_type: string
          storage_path: string
          latitude?: number | null
          longitude?: number | null
          taken_at?: string | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          trip_id?: string
          photo_type?: string
          storage_path?: string
          latitude?: number | null
          longitude?: number | null
          taken_at?: string | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trip_photos_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trip_photos_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trip_photos_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      trips: {
        Row: {
          id: string
          trip_number: string
          order_id: string
          truck_id: string | null
          driver_id: string | null
          source_id: string | null
          status: string
          price: number
          material_cost: number
          crew_cost: number
          diesel_litres_issued: number | null
          diesel_cost: number
          repayment_allocation: number
          loader_receipt_no: string | null
          assigned_at: string | null
          loaded_at: string | null
          delivered_at: string | null
          settled_at: string | null
          cancel_reason: string | null
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          trip_number?: string
          order_id: string
          truck_id?: string | null
          driver_id?: string | null
          source_id?: string | null
          status?: string
          price: number
          material_cost?: number
          crew_cost?: number
          diesel_litres_issued?: number | null
          diesel_cost?: number
          repayment_allocation?: number
          loader_receipt_no?: string | null
          assigned_at?: string | null
          loaded_at?: string | null
          delivered_at?: string | null
          settled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          trip_number?: string
          order_id?: string
          truck_id?: string | null
          driver_id?: string | null
          source_id?: string | null
          status?: string
          price?: number
          material_cost?: number
          crew_cost?: number
          diesel_litres_issued?: number | null
          diesel_cost?: number
          repayment_allocation?: number
          loader_receipt_no?: string | null
          assigned_at?: string | null
          loaded_at?: string | null
          delivered_at?: string | null
          settled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trips_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trips_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trips_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trips_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "material_sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trips_truck_id_fkey"
            columns: ["truck_id"]
            isOneToOne: false
            referencedRelation: "trucks"
            referencedColumns: ["id"]
          },
        ]
      }
      trucks: {
        Row: {
          id: string
          plate_number: string
          make: string | null
          model: string | null
          capacity_tons: number | null
          owner_type: string
          owner_name: string | null
          reference_load_photo_url: string | null
          status: string
          is_active: boolean
          created_at: string
          updated_at: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          plate_number: string
          make?: string | null
          model?: string | null
          capacity_tons?: number | null
          owner_type: string
          owner_name?: string | null
          reference_load_photo_url?: string | null
          status?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          plate_number?: string
          make?: string | null
          model?: string | null
          capacity_tons?: number | null
          owner_type?: string
          owner_name?: string | null
          reference_load_photo_url?: string | null
          status?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string | null
          created_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trucks_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      change_route_price: {
        Args: {
          p_route_id: string
          p_customer_price: number
          p_material_cost: number
          p_diesel_price_per_litre: number
          p_crew_cost: number
          p_note?: string
        }
        Returns: Database["public"]["Tables"]["route_prices"]["Row"]
      }
      set_diesel_price: {
        Args: { p_price_per_litre: number }
        Returns: Database["public"]["Tables"]["diesel_prices"]["Row"]
      }
      current_user_role: { Args: Record<PropertyKey, never>; Returns: string }
      current_driver_id: { Args: Record<PropertyKey, never>; Returns: string }
      is_assigned_driver: { Args: { p_trip_id: string }; Returns: boolean }
      next_order_number: { Args: Record<PropertyKey, never>; Returns: string }
      next_trip_number: { Args: Record<PropertyKey, never>; Returns: string }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
