"""Generate src/types/database.ts from the live local schema.

Mirrors the output shape of `supabase gen types typescript`. Run against a
database that has the migration applied:
    python3 scripts/gen-types.py "host=/tmp port=5433 user=postgres dbname=hm"
Once a Supabase project exists, prefer:
    npx supabase gen types typescript --project-id <ref> --schema public > src/types/database.ts
"""
import subprocess, sys, json

dsn = sys.argv[1]
def q(sql):
    out = subprocess.check_output(['psql', dsn, '-At', '-c', sql], text=True)
    return json.loads(out.strip() or 'null')

cols = q("""
select json_agg(x order by table_name, ordinal_position) from (
 select c.table_name, c.column_name, c.ordinal_position, c.is_nullable='YES' as nullable,
        (c.column_default is not null) as has_default, c.udt_name
 from information_schema.columns c
 join information_schema.tables t using (table_schema, table_name)
 where c.table_schema='public' and t.table_type='BASE TABLE') x""")
fks = q("""
select json_agg(x order by tbl, conname) from (
 select con.conname, cl.relname tbl, a.attname col, rcl.relname ref, ra.attname refcol,
   exists(select 1 from pg_index i where i.indrelid=con.conrelid and i.indisunique and i.indnatts=1 and i.indkey[0]=con.conkey[1]) one
 from pg_constraint con
 join pg_class cl on cl.oid=con.conrelid join pg_namespace n on n.oid=cl.relnamespace
 join pg_class rcl on rcl.oid=con.confrelid
 join pg_attribute a on a.attrelid=con.conrelid and a.attnum=con.conkey[1]
 join pg_attribute ra on ra.attrelid=con.confrelid and ra.attnum=con.confkey[1]
 where con.contype='f' and n.nspname='public' and rcl.relnamespace=n.oid) x""")

TS = {'uuid':'string','text':'string','int4':'number','int8':'number','numeric':'number',
      'bool':'boolean','timestamptz':'string','date':'string','jsonb':'Json'}
tables = {}
for c in cols:
    tables.setdefault(c['table_name'], []).append(c)

def ind(n): return '  ' * n
out = []
out.append('// Generated by scripts/gen-types.py from supabase/migrations. Do not edit by hand.')
out.append('// Shape matches `supabase gen types typescript`.\n')
out.append('export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\n')
out.append('export type Database = {')
out.append(ind(1) + 'public: {')
out.append(ind(2) + 'Tables: {')
for t in sorted(tables):
    out.append(ind(3) + f'{t}: {{')
    for kind in ('Row', 'Insert', 'Update'):
        out.append(ind(4) + f'{kind}: {{')
        for c in tables[t]:
            ts = TS[c['udt_name']] + (' | null' if c['nullable'] else '')
            opt = ''
            if kind == 'Update' or (kind == 'Insert' and (c['nullable'] or c['has_default'])):
                opt = '?'
            out.append(ind(5) + f"{c['column_name']}{opt}: {ts}")
        out.append(ind(4) + '}')
    out.append(ind(4) + 'Relationships: [')
    for f in (fks or []):
        if f['tbl'] != t: continue
        out.append(ind(5) + '{')
        out.append(ind(6) + f"foreignKeyName: \"{f['conname']}\"")
        out.append(ind(6) + f"columns: [\"{f['col']}\"]")
        out.append(ind(6) + f"isOneToOne: {'true' if f['one'] else 'false'}")
        out.append(ind(6) + f"referencedRelation: \"{f['ref']}\"")
        out.append(ind(6) + f"referencedColumns: [\"{f['refcol']}\"]")
        out.append(ind(5) + '},')
    out.append(ind(4) + ']')
    out.append(ind(3) + '}')
out.append(ind(2) + '}')
out.append(ind(2) + 'Views: { [_ in never]: never }')
out.append(ind(2) + '''Functions: {
      change_route_price: {
        Args: {
          p_route_id: string
          p_customer_price: number
          p_material_cost: number
          p_diesel_price_per_litre: number
          p_crew_cost: number
          p_note?: string
        }
        Returns: Database["public"]["Tables"]["route_prices"]["Row"]
      }
      set_diesel_price: {
        Args: { p_price_per_litre: number }
        Returns: Database["public"]["Tables"]["diesel_prices"]["Row"]
      }
      current_user_role: { Args: Record<PropertyKey, never>; Returns: string }
      current_driver_id: { Args: Record<PropertyKey, never>; Returns: string }
      is_assigned_driver: { Args: { p_trip_id: string }; Returns: boolean }
      next_order_number: { Args: Record<PropertyKey, never>; Returns: string }
      next_trip_number: { Args: Record<PropertyKey, never>; Returns: string }
    }''')
out.append(ind(2) + 'Enums: { [_ in never]: never }')
out.append(ind(2) + 'CompositeTypes: { [_ in never]: never }')
out.append(ind(1) + '}')
out.append('}\n')
out.append('''type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
''')
open('src/types/database.ts', 'w').write('\n'.join(out))
print('tables:', len(tables))
